server:
  listen: 8080
  workers: 4
  
  upstreams:
    - id: jsonplaceholder
      url: jsonplaceholder.typicode.com

    - id: dummyjson
      url: dummyjson.com
    

  headers:
    - key: x-forward-for
      value: '$ip'

    - key: Authorization
      value: 'Bearer $token'

  rules:
    - path: /test
      upstreams: 
        - dummyjson

    - path: /
      upstreams: 
        - jsonplaceholder

    